### ISSUE TITLE
Typescript missing frequency_penalty in generate configs

### ISSUE THREAD

**Issue by sangdth** [cohere-ai/cohere-node#24]
<img width="1173" alt="Screenshot 2022-03-06 at 20 37 47" src="https://user-images.githubusercontent.com/1083478/156937847-fc415207-2edd-4751-b43f-1ffeb1f7e74a.png">

**Comment by kravse** [comment]
Sorry about that. I believe this should be fixed now. @sangdth. Thanks for reporting.

**Comment by sangdth** [comment]
Thanks for the quick update!

By the way, if the `frequence_penalty` is used, we should update the one in export code also
<img width="542" alt="Screenshot 2022-03-07 at 23 56 10" src="https://user-images.githubusercontent.com/1083478/157124643-545efc05-f65e-48c9-aef6-21a3bafc2dd6.png">
.

**Comment by kravse** [comment]
> Thanks for the quick update!
> 
> By the way, if the `frequence_penalty` is used, we should update the one in export code also <img alt="Screenshot 2022-03-07 at 23 56 10" width="542" src="https://user-images.githubusercontent.com/1083478/157124643-545efc05-f65e-48c9-aef6-21a3bafc2dd6.png"> .

🤦 thats definitely a typo in the sdk, sorry about that. I've fixed and it's published in version `3.0.3`. Thanks for flagging please let me know if you find anything else, your bug reports have been helpful.
